### ISSUE TITLE
compe_nvim_lsp/source.lua:60: attempt to index local 'result' (a nil value)

### ISSUE THREAD

**Issue by tami5** [hrsh7th/nvim-compe#2]
Hi @hrsh7th,
I got to say, after going through many completion plugins yours offered the best experience. am amazed of how light and fast it feels, also NO FLICKERING which is so amazing.

During testing i got the following error whenever I do one of the following
- type ./... to complete file path
- after completing lsp source function and opening paren (..

```viml
Error executing vim.schedule lua callback: ...pack/packer/opt/nvim-compe/lua/compe_nvim_lsp/source.lua:60: attempt to index local 'result' (a nil value)
```

My configuration:

```lua
  vim.o.pumheight = 10
  vim.cmd('set completeopt=menuone,noinsert,noselect')
  vim.cmd('packadd nvim-compe')
  vim.cmd'let g:compe_enabled = v:true'
  vim.cmd'let g:compe_min_length = 1'
  require'compe_nvim_lsp'.attach()
  require'compe':register_lua_source('buffer', require'compe_buffer')
  vim.cmd[[call compe#source#vim_bridge#register('path', compe_path#source#create())]]
  bind.i({
    {'<cr>', [[compe#confirm('<CR>')]], {expr = true}},
    {'<C-e>', [[compe#close('<C-e>'))]], {expr = true}},
    {'<C-Space>', [[<C-r>=compe#complete()<CR>]], {expr = true}},
    {'<C-j>', [[pumvisible() ? "\<C-n>" : "\<C-j>"]], { expr = true}},
    {'<C-k>', [[pumvisible() ? "\<C-p>" : "\<C-k>"]], { expr = true}},
    {'<Tab>', [[pumvisible() ? "\<C-n>" : "\<Tab>"]], { expr = true}},
    {'<S-Tab>', [[pumvisible() ? "\<C-p>" : "\<S-Tab>"]], { expr = true}},
  })

```

I'm using nvim built in lsp 

Seriously amazing plugin and I believe it might be the next best thing. Looking forward to develop sources for it

**Comment by tami5** [comment]
Also, after the above error message going to insert is no longer allowed: `E523: Not allowed here` error

**Comment by tami5** [comment]
path completion doesn't work, typing ./ does trigger path completion

**Comment by hrsh7th** [comment]
path completion problem should be fixed now.

**Comment by tami5** [comment]
It is, thanks @hrsh7th

**Comment by tami5** [comment]
Still facing some issues with nvim-compe and telescope. Not sure why but adding autocmd I mentioned above didn't stop nvim_compe from being activated in Telescope filetype. Is there a better way. 

Thanks

**Comment by hrsh7th** [comment]
OK. I will investigate it.

**Comment by hrsh7th** [comment]
I think the problem was fixed now.
Could you test it?

**Comment by tami5** [comment]
Oh yes so much better no need for autocmds any more. Thanks so much @hrsh7th the issue is resolved.
