### ISSUE TITLE
No completion options for specific LSP

### ISSUE THREAD

**Issue by zegervdv** [hrsh7th/nvim-compe#284]
I've switched from completion-nvim and now I am not getting completion options with a specific LSP. (It works fine for pyright).

I have been comparing the traces the LSP shows and I think I found the difference.
I noticed in the `textDocument/completion` request nvim-compe sends out, there is a `context.triggerKind` field, which is not present in completion-nvim.

For some unknown reason this seems to prevent the LSP from actually returning any completion options.
Is there a way to remove this field from the completion request or is this a bug in the LSP or LSP config?

**Comment by zegervdv** [comment]
I removed the `context.triggerKind` but that did not solve it.

But I noticed what probably is the real difference: completion-nvim sends a new `textDocument/completion` event upon receiving the response to the previous one. The first response from the LSP is empty, and it seems compe is not asking for any more completions after that.

**Comment by hrsh7th** [comment]
@zegervdv Which server do you have a problem?

**Comment by zegervdv** [comment]
It's a commercial one that requires a license :/

**Comment by hrsh7th** [comment]
Hm... I always test nvim-compe with many servers.

- typescript-language-server
- gopls
- vscode-json-language-server
- vscode-html-language-server
- vscode-css-language-server
- intelephense
- rust-analyzer
- vim-language-server
- clangd

But I don't have this problem...

**Comment by zegervdv** [comment]
I understand it is hard to debug without access.
It is a java based language server, probably using lsp4j.

I do have some traces from the LSP log which may help?

```
// Completion-nvim
[Trace - 06:24:30 PM] Received request 'textDocument/completion - (3)'
Params: {
  "textDocument": {
    "uri": "file:[REDACTED]"
  },
  "position": {
    "line": 319,
    "character": 5
  }
}


[Trace - 06:24:31 PM] Received notification 'textDocument/didChange'
Params: {
  "textDocument": {
    "version": 9,
    "uri": "file:[REDACTED]"
  },
  "contentChanges": [
    {
      "range": {
        "start": {
          "line": 319,
          "character": 5
        },
        "end": {
          "line": 319,
          "character": 5
        }
      },
      "rangeLength": 0,
      "text": "_"
    }
  ]
}


[Trace - 06:24:31 PM] Sending response 'textDocument/completion - (3)'. Processing request took 304ms
Result: null


[Trace - 06:24:31 PM] Received request 'textDocument/completion - (4)'
Params: {
  "textDocument": {
    "uri": "file:[REDACTED]"
  },
  "position": {
    "line": 319,
    "character": 6
  }
}
```
compe does not send a new `completion` after the first response, while completion-nvim keeps on sending requests until it finally returns a response with data.
```
// Compe
[Trace - 08:44:26 AM] Received request 'textDocument/completion - (2)'
Params: {
  "textDocument": {
    "uri": "file:[REDACTED]"
  },
  "position": {
    "line": 319,
    "character": 5
  }
}


[Trace - 08:44:27 AM] Received notification 'textDocument/didChange'
Params: {
  "textDocument": {
    "version": 8,
    "uri": "file:[REDACTED]"
  },
  "contentChanges": [
    {
      "range": {
        "start": {
          "line": 319,
          "character": 5
        },
        "end": {
          "line": 319,
          "character": 5
        }
      },
      "rangeLength": 0,
      "text": "_"
    }
  ]
}


[Trace - 08:44:27 AM] Sending response 'textDocument/completion - (2)'. Processing request took 639ms
Result: null


[Trace - 08:44:27 AM] Received notification 'textDocument/didChange'
Params: {
  "textDocument": {
    "version": 9,
    "uri": "file:[REDACTED]"
  },
  "contentChanges": [
    {
      "range": {
        "start": {
          "line": 319,
          "character": 5
        },
        "end": {
          "line": 319,
          "character": 6
        }
      },
      "rangeLength": 1,
      "text": ""
    }
  ]
}
```

**Comment by zegervdv** [comment]
A test with VSCode shows it even doesn't wait for the `textDocument/completion` responses, it just keeps sending requests while typing.

**Comment by zegervdv** [comment]
It seems compe only sends the completion request once per word(boundary), but the LSP will not give any options when the inserted text is still empty.
VSCode and nvim-completion send multiple requests while you are typing so eventually some suggestions do come up.

Is there a way to make compe send multiple requests while typing? Even just a quick hack to test my assumption?

**Comment by gasacchi** [comment]
this also appear with purescript LSP.
when i try to type something, i got error message:

    E5100: Cannot convert given lua table: table should either have a sequence of positive integer keys or contain only string keys                        
    Error executing vim.schedule lua callback: error converting argument 2

**Comment by zegervdv** [comment]
I forgot about the `compe#completion()` mapping. If I trigger that manually it sends new requests to the LSP and I get completion options.

@hrsh7th is this the expected behaviour? To only send one request when entering insert mode and trigger it manually later? Or should new requests be send while typing?

**Comment by hrsh7th** [comment]
In LSP spec, your expected behavior depends on `isIncomplete` flag that returns from LanguageServer.

I tested `eclipse.jdtls` but it does not return `isIncomplete` so compe does not send a request on each keypress to `eclipse.jdtls`.

**Comment by zegervdv** [comment]
that seems to be set:
```
[Trace - 6:47:43 PM] Received response 'textDocument/completion - (91)' in 134ms.
Result: {
    "isIncomplete": true,
    "items": [
        {
```

**Comment by zegervdv** [comment]
but only after a second or third request, else it responds with `Result: null`, which probably makes compe think there are no options (or `isIncomplete = false`)  and stop requesting? 

Would it be possible (through a config setting perhaps) to keep requesting when the results are empty?

**Comment by hrsh7th** [comment]
Insightful.

Yes. Probably, compe would stop requesting if received `Result: null`.

In compe, this handling is one of the most complexes.

https://github.com/hrsh7th/nvim-compe/blob/master/lua/compe/source.lua#L65

Hm... I want to know what VSCode does it.

**Comment by zegervdv** [comment]
As far as I can see from the logging it seems VSCode sends new requests after receiving `Result: null`.

**Comment by hrsh7th** [comment]
@zegervdv Sorry. I think it solved by https://github.com/hrsh7th/nvim-compe/commit/2dada3065e938a6b467481618d1ee9c1ef08e42c

**Comment by zegervdv** [comment]
@hrsh7th I still get the same behaviour :( 

I tried to get some debug prints from the `completion` callback (in lua/compe_nvim_lsp/source.lua:43), but it never seemed to even call that function.
So I started testing with the `vim.lsp.set_log_level("debug")` and found something else:
```
[ DEBUG ] 2021-04-02T17:50:17+0200 ] ...neovim/HEAD-0f7b6b2_2/share/nvim/runtime/lua/vim/lsp.lua:711 ]	"LSP[name]"	"client.request"	1	"textDocument/completion"	{  context = {    triggerKind = 1  },  position = {    character = 3,    line = 122  },  textDocument = {    uri = "[REDACTED]"  }}	<function 1>	nil
[ DEBUG ] 2021-04-02T17:50:17+0200 ] ...im/HEAD-0f7b6b2_2/share/nvim/runtime/lua/vim/lsp/rpc.lua:391 ]	"rpc.send.payload"	{  id = 3,  jsonrpc = "2.0",  method = "textDocument/completion",  params = {    context = {      triggerKind = 1    },    position = {      character = 3,      line = 122    },    textDocument = {      uri = "[REDACTED]"    }  }}
[ DEBUG ] 2021-04-02T17:50:18+0200 ] ...neovim/HEAD-0f7b6b2_2/share/nvim/runtime/lua/vim/lsp.lua:828 ]	"on_lines bufnr: 1, changedtick: 9, firstline: 122, lastline: 123, new_lastline: 123, old_byte_size: 4, old_utf32_size: 4, old_utf16_size: 4"	{ "  mi" }
[ DEBUG ] 2021-04-02T17:50:18+0200 ] ...im/HEAD-0f7b6b2_2/share/nvim/runtime/lua/vim/lsp/rpc.lua:391 ]	"rpc.send.payload"	{  jsonrpc = "2.0",  method = "textDocument/didChange",  params = {    contentChanges = { {        range = {          end = {            character = 3,            line = 122          },          start = {            character = 3,            line = 122          }        },        rangeLength = 0,        text = "i"      } },    textDocument = {      uri = "[REDACTED]",      version = 9    }  }}
[ DEBUG ] 2021-04-02T17:50:18+0200 ] ...neovim/HEAD-0f7b6b2_2/share/nvim/runtime/lua/vim/lsp.lua:828 ]	"on_lines bufnr: 1, changedtick: 10, firstline: 122, lastline: 123, new_lastline: 123, old_byte_size: 5, old_utf32_size: 5, old_utf16_size: 5"	{ "  mif" }
[ DEBUG ] 2021-04-02T17:50:18+0200 ] ...im/HEAD-0f7b6b2_2/share/nvim/runtime/lua/vim/lsp/rpc.lua:391 ]	"rpc.send.payload"	{  jsonrpc = "2.0",  method = "textDocument/didChange",  params = {    contentChanges = { {        range = {          end = {            character = 4,            line = 122          },          start = {            character = 4,            line = 122          }        },        rangeLength = 0,        text = "f"      } },    textDocument = {      uri = "[REDACTED]",      version = 10    }  }}
[ DEBUG ] 2021-04-02T17:50:18+0200 ] ...im/HEAD-0f7b6b2_2/share/nvim/runtime/lua/vim/lsp/rpc.lua:492 ]	"decoded"	{  error = {    code = -32800,    message = "The request (id: 3, method: 'textDocument/completion') has been cancelled"  },  id = 3,  jsonrpc = "2.0"}
[ DEBUG ] 2021-04-02T17:50:18+0200 ] ...im/HEAD-0f7b6b2_2/share/nvim/runtime/lua/vim/lsp/rpc.lua:530 ]	"Received cancellation ack"	{  error = {    code = -32800,    message = "The request (id: 3, method: 'textDocument/completion') has been cancelled"  },  id = 3,  jsonrpc = "2.0"}
```

At some point the server (I think?) sends a cancellation (or maybe the `Results: null` is interpreted as such) and that probably means the callback is never called. 

I assume if the callback is never called, your fix will not work in my case?
