### ISSUE TITLE
backspace causes flickering 

### ISSUE THREAD

**Issue by tami5** [hrsh7th/nvim-compe#30]

**Comment by hrsh7th** [comment]
Maybe implemented it.

**Comment by tami5** [comment]
I’ll test it later and report back. Thanks @hrsh7th

**Comment by elianiva** [comment]
hmm, I got an issue after this commit.
https://streamable.com/38nu2c

Notice the last few seconds, it's not me deleting `d` and typing it again, I can't delete the previous word if the popup is visible. Here's my [config](https://github.com/elianiva/dotfiles/blob/master/nvim/.config/nvim/lua/plugins/_completion.lua) for nvim-compe.

**Comment by hrsh7th** [comment]
@elianiva Thank you for your report.
I've fixed it maybe.

**Comment by elianiva** [comment]
Can confirm that it's gone, but I still can't delete the previous word unfortunately.

**Comment by hrsh7th** [comment]
It's very weird and I can't reproduce.

Could you provide a result of `imap <BS>` ?

**Comment by elianiva** [comment]
It gives me this.
![image](https://user-images.githubusercontent.com/51877647/100205862-3a6f9f80-2f38-11eb-9a45-a54de2eb8e2a.png)

**Comment by hrsh7th** [comment]
Sorry. Could you test with `:imap <BS>` ?

**Comment by elianiva** [comment]
![image](https://user-images.githubusercontent.com/51877647/100207054-b4ecef00-2f39-11eb-9996-8b29fd25d45c.png)
ok, it gives me this.

**Comment by hrsh7th** [comment]
Oh... It is the same result as mine...
I will consider it

**Comment by tami5** [comment]
@elianiva why use this ? doesn't completion on backspace works naturally without this mapping? or is there additional stuff it brings?

**Comment by elianiva** [comment]
I didn't set that mapping. It came from lexima.

**Comment by tami5** [comment]
ohhhh I see

**Comment by kristijanhusak** [comment]
@hrsh7th I noticed from commit https://github.com/hrsh7th/nvim-compe/commit/0ccef7c6558a0f00adea4e892c6ec58495f6fc3a that "tags" source is misbehaving. It won't properly show results util you write out the whole thing, and even then gives wrong results. Commit before that one works fine.

**Comment by hrsh7th** [comment]
@kristijanhusak Thank you for your report.

This behavior is intentional.
For example, the buffer source should be invoked once on one alphabetical char typed (If we gather words on each key press, It isn't efficient because buffer words would not change during one completion.

Anyway, I want to know if the tags source should be called on each key press.

If so, it will fix easily.
nvim-compe can take `incomolete = true` for the callback argument on `a:args.callback({ items = items; incomplete = true })`.

**Comment by kristijanhusak** [comment]
Well, `getcompletion()` function is built-in function that is not async, so I guess we need it on each key press.
Will `incomplete = true` constantly call this or only if input changes?

**Comment by hrsh7th** [comment]
`incomplete = true` makes being to invoke `getcompletion()` on each key press.

The `incomolete = false` means `should use cache`.

**Comment by kristijanhusak** [comment]
Ok. I just tried it, it works when I add `incomplete = true`, so that should fix the issue. Thanks.

**Comment by elianiva** [comment]
Can confirm this is somehow caused by lexima. After removing lexima it works fine with latest commit. I was going to remove lexima at some point anyway, so this might be the time :laughing:

**Comment by hrsh7th** [comment]
> Can confirm this is somehow caused by lexima. After removing lexima it works fine with latest commit. I was going to remove lexima at some point anyway, so this might be the time 😆

Thank you for your investigation.
But I'm using lexima... and backspace works fine now...

**Comment by hrsh7th** [comment]
@elianiva I think this issue can be closed.

**Comment by elianiva** [comment]
Sure, thanks for fixing it!
