### ISSUE TITLE
flickering with `compe_auto_preselect = true`

### ISSUE THREAD

**Issue by tami5** [hrsh7th/nvim-compe#32]
Hey, I'm starting to rely on snippets a lot, and I decide to use preselect, it has flickering issue. The selection flickers with each litter typed.

**Comment by hrsh7th** [comment]
Thank you. It's a bug.

But I notice that will be flicker when press backspace... and it maybe can't fix.

Anyway, it shouldn't be flicked when pressing normal alphabetical chars.

**Comment by hrsh7th** [comment]
This problem should be fixed by https://github.com/hrsh7th/nvim-compe/commit/7629c90cde2ec8ed6ffc5ffb69e9614742a84512

**Comment by tami5** [comment]
@hrsh7th still the issue on going, now its like double flickering

**Comment by hrsh7th** [comment]
Currently, nvim-compe is invoke `complete` and `vim.api.nvim_select_popupmenu_item` in same synchronous context so I don't know the reason of this problem... 🤔

**Comment by smartding** [comment]
@tami5, just one quick question, what completion engine are you using? I used ultisnips before, but nvim-compe doesn't seem to work with ultisnips.

**Comment by hrsh7th** [comment]
@smartding If you using with ultisnips, we should create `compe-ultisnips` source.
And @tami5 uses `vim-vsnip`. vsnip source is provided built-in (because it was created by me 😆

**Comment by hrsh7th** [comment]
I found `nvim_select_popupmenu_item` causes flicker and I believe it can't be fixed.

coc.nvim realized it by no `nvim_select_popupmenu_item`.
However coc.nvim expands item automatically when to press `<CR>` key by user.

**Comment by hrsh7th** [comment]
> I found nvim_select_popupmenu_item causes flicker and I believe it can't be fixed.

> coc.nvim realized it by no nvim_select_popupmenu_item.
> However coc.nvim expands item automatically when to press <CR> key by user.

It will flicker when to press `<CR>`.

**Comment by hrsh7th** [comment]
I'm guessing the reason for flicker is some other decoration api's redraw (e.g.: sign_place, virtualtext, underline ...)

**Comment by tami5** [comment]
Damn it , can we have custom alternative? what functionality do we need? Also can u explain the issue more, thanks

**Comment by hrsh7th** [comment]
My guessing is wrong maybe.
Probably we can fix it.

**Comment by hrsh7th** [comment]
It caused by Olical/conjure.

**Comment by tami5** [comment]
hmmmm, I'm going to patch rebuild and report back

**Comment by tami5** [comment]
@hrsh7th is this the patch : 

```diff
@@ -783,6 +783,8 @@ do
       bufnr, changedtick, firstline, lastline, new_lastline, old_byte_size, old_utf32_size, old_utf16_size),
       nvim_buf_get_lines(bufnr, firstline, new_lastline, true)
     )
+     -- Don't send buffer changes to the server while any kind of completion is active
+     if vim.fn.complete_info().mode ~= "" then return end
 
     -- Don't do anything if there are no clients attached.
     if tbl_isempty(all_buffer_active_clients[bufnr] or {}) then
@@ -792,8 +794,6 @@ do
     util.buf_versions[bufnr] = changedtick
     -- Lazy initialize these because clients may not even need them.
     local incremental_changes = once(function(client)
-      local size_index = encoding_index[client.offset_encoding]
-      local length = select(size_index, old_byte_size, old_utf16_size, old_utf32_size)
       local lines = nvim_buf_get_lines(bufnr, firstline, new_lastline, true)
       -- This is necessary because we are specifying the full line including the
       -- newline in range. Therefore, we must replace the newline as well.
@@ -805,7 +805,6 @@ do
           start = { line = firstline, character = 0 };
           ["end"] = { line = lastline, character = 0 };
         };
-        rangeLength = length;
         text = table.concat(lines, '\n');
       };
     end)
@@ -820,13 +819,7 @@ do
       local changes
       if text_document_did_change == protocol.TextDocumentSyncKind.None then
         return
-      --[=[ TODO(ashkan) there seem to be problems with the byte_sizes sent by
-      -- neovim right now so only send the full content for now. In general, we
-      -- can assume that servers *will* support both versions anyway, as there
-      -- is no way to specify the sync capability by the client.
-      -- See https://github.com/palantir/python-language-server/commit/cfd6675bc10d5e8dbc50fc50f90e4a37b7178821#diff-f68667852a14e9f761f6ebf07ba02fc8 for an example of pyls handling both.
-      --]=]
-      elseif true or text_document_did_change == protocol.TextDocumentSyncKind.Full then
+      elseif text_document_did_change == protocol.TextDocumentSyncKind.Full then
         changes = full_changes(client)
       elseif text_document_did_change == protocol.TextDocumentSyncKind.Incremental then
         changes = incremental_changes(client)

```

I've applied it and it doesn't seem to improve the issue.

**Comment by hrsh7th** [comment]
Thank you for your investigation.

I found the behavior becomes better by `on_text_changed` throttling (so the problem might be caused by heavy processing)

I've pushed the improvements.
Could you test with latest master?

**Comment by hrsh7th** [comment]
I'm happy to latest nvim-compe's behavior .

**Comment by tami5** [comment]
Oh wow, that magical, no more flickering. How did you achieve that, what was the problem?. Great work @hrsh7th

**Comment by hrsh7th** [comment]
Actually, I don't know the root cause.

But I found if enable nvim-lsp's `incremental sync`, it helps to this problem.

So I guess the cause is performance. So I add throttling for completion.

**Comment by tami5** [comment]
Nice, but the issue is not only fixed for nvim-lsp, also for everything else btw.

**Comment by hrsh7th** [comment]
I'm not really sure why. Maybe it was my code.

Anyway, I love current behavior. Now, I feel nvim-compe smooth and lightweight.

**Comment by tami5** [comment]
> Anyway, I love current behavior. Now, I feel nvim-compe smooth and lightweight.

VERRRRRYYYYYY, the best there is :heart: 

Any updates on the lua builtin source :D

**Comment by hrsh7th** [comment]
I'm now implementing.

**Comment by tami5** [comment]
Nice, make sure that the user can define some type of variable that defines filetypes. such as luapad.lua or fennel. like `filetypes = vim.g.compe_lua_filetypes or {lua'}`

**Comment by hrsh7th** [comment]
I will consider and left some notes to #37

**Comment by hrsh7th** [comment]
I was implemented nvim-lua source.

**Comment by tami5** [comment]
@hrsh7th I'm notcing that the filcker still exists, have noticed that? It is better then before but when typing fast and backspace it flickers on every letter. :(

**Comment by tami5** [comment]
Also for some reason the lua source seems to be working outside the specified file types

**Comment by hrsh7th** [comment]
`let g:compe_throttle_time = 200` would be help for flicker.

Lua source should be fixed now.

**Comment by hrsh7th** [comment]
The Lua source broken now... (we should change `filetype` to `filetypes`

**Comment by tami5** [comment]
g:compe_throttle_time settings to 200 haven't do much unfortunately still the issue persists

**Comment by hrsh7th** [comment]
It's weird... we should inderstand root cause...
