### ISSUE TITLE
Behavior when `insertText` is empty

### ISSUE THREAD

**Issue by dcampos** [hrsh7th/nvim-compe#467]
#### Checkhealth

Put result of `:checkhealth compe`.

```
health#compe#check
========================================================================
## compe:snippet
  - OK: snippet engine detected.

## compe:mapping
  - OK: `compe#complete` is mapped: (`i  <C-Space>   * compe#complete('<C-Space>')`)
  - OK: `compe#confirm` is mapped: (`i  <CR>        * compe#confirm('<CR>')`)
  - OK: `compe#close` is mapped: (`i  <C-E>       * pumvisible() ? compe#close('<C-E>') : "\<end>"`)
  - OK: `compe#scroll` is mapped: (`i  <M-k>       * compe#scroll({ 'delta': -4 })`)
```

#### Describe the bug

When the `insertText` attribute of an LSP completion item is empty (`''`), compe doesn't use the `label` field as I believe it should according to the LSP documentation:

```
	/**
	 * A string that should be inserted into a document when selecting
	 * this completion. When `falsy` the label is used as the insert text
	 * for this item.
	 * [...]
	 */
	insertText?: string;
```

I found this bug while working on a Godot (GDScript) project. Godot sometimes returns an empty insertText. For instance, if I type `event.dev<cursor>` and choose to complete `device`, compe deletes the `dev` part, so the text is back to `event.<cursor>`.

The completion item returned by the language server is this:

```
{'label': 'device', 'data': {'textDocument': {'uri': 'file://...'}, 'position': {'charac
ter': 10, 'line': 9}}, 'deprecated': v:false, 'detail': '', 'preselect': v:false, 'insertText': '', 'sortText': '',
 'documentation': {'kind': 'markdown', 'value': '^Ivar InputEvent.device: int^@^@The event''s device ID.^@^@**Note:
** This device ID will always be `-1` for emulated mouse input from a touchscreen. This can be used to distinguish 
emulated mouse input from physical mouse input.^@^@'}, 'command': {'title': '', 'command': ''}, 'kind': 10, 'filter
Text': ''}
```

#### To Reproduce

Steps to reproduce the behavior with the [minimal config](https://github.com/hrsh7th/nvim-compe/blob/master/misc/minimal.vim):

1. Enable the GDScript language server
2. Open a project in Godot
3. Open a GDScript file from the same project
4. Try completing a property of some object. The code below may serve as an example:

```gdscript
func _input(event):
	event.dev
```

#### Actual behavior

When a completion item has an empty `insertText` (and isn't a `textEdit`), compe inserts an empty string instead of completing with the selected completion item.

#### Expected behavior

I believe compe should insert the value of `label` when there is no text in `insertText`, because an empty string should still be considered 'falsy'.

**Comment by hrsh7th** [comment]
Thank you for your report. I've fixed it.

**Comment by dcampos** [comment]
Thanks for looking into this. I'm still experiencing the wrong behavior though.

It looks like compe is still using the empty `insertText` for completion:

https://github.com/hrsh7th/nvim-compe/blob/d35f5fcece6dc44d28646dbb9c6184eaeec82c8f/autoload/vital/_compe/VS/LSP/CompletionItem.vim#L158-L166

I tried the patch below and it worked for me:

```diff
diff --git a/autoload/vital/_compe/VS/LSP/CompletionItem.vim b/autoload/vital/_compe/VS/LSP/CompletionItem.vim
index 8414c2f..9dfd022 100644
--- a/autoload/vital/_compe/VS/LSP/CompletionItem.vim
+++ b/autoload/vital/_compe/VS/LSP/CompletionItem.vim
@@ -155,7 +155,10 @@ function! s:_get_expansion(args) abort
     endif
   else
     let l:inserted = strcharpart(l:current_line, l:suggest_position.character, l:current_position.character - l:suggest_position.character)
-    let l:new_text = get(l:completion_item, 'insertText', l:completion_item.label)
+    let l:new_text = get(l:completion_item, 'insertText', '')
+    if !l:new_text
+        let l:new_text = l:completion_item.label
+    endif
     if s:_trim_tabstop(l:new_text) !=# l:inserted
       return {
       \   'overflow_before': l:request_position.character - l:suggest_position.character,

```

I can send it as a pull request if needed.

**Comment by dcampos** [comment]
It works now. Thank you once again!
