### ISSUE TITLE
Document may or may not be displayed

### ISSUE THREAD

**Issue by hrsh7th** [hrsh7th/nvim-compe#69]
See #42 

Please information if anyone reproduces it.

**Comment by alexaandru** [comment]
I can confirm, I don't see any documentation for completions, I only see the completions. Tried in Go, Vim and Lua files - I have the LSP working for all of them, but no docs when using completion. I get docs just fine if I call it directly (for example using `:lua vim.lsp.buf.hover()`) so LSP works, I just don't see it when using completion.

**Comment by tami5** [comment]
@alexaandru yep exactly what I experienced. Thanks for confirming

**Comment by alexaandru** [comment]
Don't mention it, happy to help with what I can.

For the record, this is my config:

```Lua
require'compe'.setup {
  enabled = true,
  min_length = 2,
  preselect = 'enable', -- 'disable' | 'always'
  source = {path = true, buffer = true, nvim_lsp = true},
}
```

**Comment by hrsh7th** [comment]
In my environment, this issue does not reproduce so I want to minimal repro or more detailed investigation for it.

I think it is the higher priority.

**Comment by alexaandru** [comment]
Sure, here it is:

My environment is:
- Ubuntu 20.04.2 LTS
- NVIM v0.5.0-dev+1053-g459a6c845
- nvim-compe https://github.com/hrsh7th/nvim-compe/commit/50b6d3

Given this nvim config:

```VimL
packadd nvim-lspconfig
packadd nvim-compe

lua << END
require'lspconfig'.vimls.setup{}
require'compe'.setup {
  enabled = true,
  preselect = 'enable',
  source = {nvim_lsp = true},
}
END
```

if I run `nvim -u test.vim test.vim` and then start editing it, I do get completions but no documentation. If I go on an identifier (say `packadd`) and I run `:lua vim.lsp.buf.hover()` I do get the documentation, so LSP works.

You can see the behavior I expect in here https://github.com/hrsh7th/nvim-compe/issues/76 in the 1st clip, when it navigates through the LSP completion options, to the right (it's cut off, you can only see a little) of the completions "window", there is a second window with documentation, sync'ed to the currently selected completion item. That is what I would expect to see in this case as well.

**Comment by hrsh7th** [comment]
```viml
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !isdirectory(s:plug_dir)
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
  let s:installed = v:true
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-compe'
Plug 'neovim/nvim-lspconfig'
call plug#end()
PlugInstall | quit

" Options here.

lua << END
require'lspconfig'.vimls.setup{}
require'compe'.setup {
  enabled = true,
  preselect = 'enable',
  source = {nvim_lsp = true},
}
END
```

I tried with this configuration but I couldn't get reproduce.
Hm....

**Comment by hrsh7th** [comment]
https://user-images.githubusercontent.com/629908/106269389-cae79a80-626f-11eb-9775-823423e8a4b3.mp4

**Comment by hrsh7th** [comment]
By the way, the `textDocument/hover` (a.k.a `lua vim.lsp.buf.hover()`) does not same as `completionItem/resolve` (a.k.a `completion-documentation` .

If the LSP server returns `textDocument/hover` but not `completionItem/resolve`, it is valid behavior on LSP.

**Comment by hrsh7th** [comment]
The @tami5 case would be bug with nvim-compe may be. because he's screenshot represents the documentation may or may not be displayed on `same` item.

**Comment by alexaandru** [comment]
So, exactly what I see in your screen recording is what I would expect as well. And I am not getting that, here is what I get instead:

https://user-images.githubusercontent.com/85237/106280527-b93dcd00-6246-11eb-8def-e6f3c985a256.mov

**Comment by hrsh7th** [comment]
Oh, I found the cause may be.
You might not use `<C-n>`/`<C-p>` but use `<Up>`/`<Down>`.

The vim does not fire `CompleteChanged` by `<Up>`/`<Down>`.

**Comment by hrsh7th** [comment]
Hm... the `CompleteChanged` seems fired by `<Up>`/`<Down>` but `documentation.vim` checks `compe#_is_selected_manually` so it is ignored.

Probably, we can solve it but it take a time.

**Comment by alexaandru** [comment]
You are right, that was it! :) If I use `<C-n>`/`<C-p>` it works! :) Interestingly, if I use that 1st, then it ALSO works for `<Up>`/`<Down>`. All I have to do is, use `<C-n>`/`<C-p>` once, to "activate it", and then it works fine :-) Progress! :-)

**Comment by cloggier** [comment]
I had up and down mapped to '<c-n>' and '<c-p>' for that very reason (was also required for completion.nvim)but it still won't show documentation.

**Comment by hrsh7th** [comment]
this issue will be solved by #97

**Comment by hrsh7th** [comment]
Fixed

**Comment by cloggier** [comment]
I am afraid I still don't get any documents for sumneko Lua server.

**Comment by hrsh7th** [comment]
Reproduced... I will investigate it.

**Comment by hrsh7th** [comment]
I found the cause.

The sumneko_lua returns capabilities as `resolveSupport=false` so nvim-compe does not send `completionItem/resolve`.

**Comment by hrsh7th** [comment]
I have no solution for it... investigating...
